In [1]:
#problem1 
#create 2d NumPy array
import numpy as np

arr = np.random.randint(1, 51, size=(5, 4))
print("Array:\n", arr)

Array:
 [[49 27 27  9]
 [20 48  7 13]
 [ 1 46  5 21]
 [20  4 31 36]
 [26  8 18 28]]


In [2]:
#extract anti- diagonal
anti_diagonal = [arr[i, -1 - i] for i in range(min(arr.shape))]
print("Anti-diagonal:", anti_diagonal)


Anti-diagonal: [9, 7, 46, 20]


In [3]:
#max  value in each row
row_max = np.max(arr, axis=1)
print("Max in each row:", row_max)

Max in each row: [49 48 46 36 28]


In [4]:
#array containing elements ≤ mean
mean_value = np.mean(arr)
new_arr = arr[arr <= mean_value]
print("Elements ≤ mean (", mean_value, "):", new_arr)

Elements ≤ mean ( 22.2 ): [ 9 20  7 13  1  5 21 20  4  8 18]


In [5]:
#boundary traversal function
def numpy_boundary_traversal(matrix):
    top = matrix[0, :]
    right = matrix[1:-1, -1]
    bottom = matrix[-1, ::-1]
    left = matrix[-2:0:-1, 0]
    return list(top) + list(right) + list(bottom) + list(left)

print("Boundary traversal:", numpy_boundary_traversal(arr))


Boundary traversal: [49, 27, 27, 9, 13, 21, 36, 28, 18, 8, 26, 20, 1, 20]


In [6]:
# problem2
#create 1-D NumPy array and round
arr = np.random.uniform(0, 10, 20)
arr = np.round(arr, 2)
print("Rounded array:", arr)


Rounded array: [9.13 4.1  3.05 2.09 9.8  5.6  2.17 4.14 2.63 1.32 1.09 9.63 0.99 2.5
 4.64 0.42 9.51 7.58 7.86 2.19]


In [7]:
#min, max, median
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Median:", np.median(arr))


Min: 0.42
Max: 9.8
Median: 3.5749999999999997


In [8]:
#Replace all elements less than 5 with their squares
arr_modified = np.where(arr < 5, np.round(arr**2, 2), arr)
print("Modified array:", arr_modified)


Modified array: [ 9.13 16.81  9.3   4.37  9.8   5.6   4.71 17.14  6.92  1.74  1.19  9.63
  0.98  6.25 21.53  0.18  9.51  7.58  7.86  4.8 ]


In [9]:
# Alternate sort function
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    result = []
    i, j = 0, len(sorted_array) - 1
    while i <= j:
        result.append(sorted_array[i])
        if i != j:
            result.append(sorted_array[j])
        i += 1
        j -= 1
    return np.array(result)

print("Alternating sort:", numpy_alternate_sort(arr))


Alternating sort: [0.42 9.8  0.99 9.63 1.09 9.51 1.32 9.13 2.09 7.86 2.17 7.58 2.19 5.6
 2.5  4.64 2.63 4.14 3.05 4.1 ]


In [10]:
#problem3
# create dataframe
import pandas as pd
import random

names = ['Student'+str(i) for i in range(1, 11)]
subjects = ['Math', 'Science', 'English', 'History']
data = {
    'Name': names,
    'Subject': random.choices(subjects, k=10),
    'Score': np.random.randint(50, 101, size=10),
    'Grade': [''] * 10
}
df = pd.DataFrame(data)


In [11]:
#assign grades
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)
print(df)


        Name  Subject  Score Grade
0   Student1     Math     53     F
1   Student2     Math     68     D
2   Student3     Math     54     F
3   Student4     Math     52     F
4   Student5  History     99     A
5   Student6  History     50     F
6   Student7  History     79     C
7   Student8  English     83     B
8   Student9     Math     69     D
9  Student10  Science     80     B


In [12]:
#sort by score
print(df.sort_values(by='Score', ascending=False))


        Name  Subject  Score Grade
4   Student5  History     99     A
7   Student8  English     83     B
9  Student10  Science     80     B
6   Student7  History     79     C
8   Student9     Math     69     D
1   Student2     Math     68     D
2   Student3     Math     54     F
0   Student1     Math     53     F
3   Student4     Math     52     F
5   Student6  History     50     F


In [13]:
#average per subject
print(df.groupby('Subject')['Score'].mean())


Subject
English    83.0
History    76.0
Math       59.2
Science    80.0
Name: Score, dtype: float64


In [14]:
#filter A and B 
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print(pandas_filter_pass(df))


        Name  Subject  Score Grade
4   Student5  History     99     A
7   Student8  English     83     B
9  Student10  Science     80     B


In [15]:
#problem 4
#create dataframe
positive_reviews = ["Good movie!" for _ in range(50)]
negative_reviews = ["Bad movie!" for _ in range(50)]
reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})


In [16]:
# vectorization and train test split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [17]:
# train naive bayes and test 
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 1.0


In [18]:
#predict sentiment function
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    return model.predict(review_vec)[0]

print(predict_review_sentiment(model, vectorizer, "Amazing movie!"))


negative


In [19]:
# problem 5
#dataset and tfidf vectorizer
feedback = ["Good product!" for _ in range(50)] + ["Bad experience." for _ in range(50)]
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Feedback': feedback, 'Label': labels})

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = tfidf.fit_transform(df['Feedback'])
y = df['Label']


In [20]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


In [21]:
#logistics regression and metrices
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Precision:", precision_score(y_test, y_pred, pos_label='good'))
print("Recall:", recall_score(y_test, y_pred, pos_label='good'))
print("F1-score:", f1_score(y_test, y_pred, pos_label='good'))


Precision: 1.0
Recall: 1.0
F1-score: 1.0


In [22]:
#preprocess and vectorize function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

print(text_preprocess_vectorize(["Terrible experience"], tfidf).toarray())


[[0. 1. 0. 0.]]
